# Generated by Django 5.2.8 on 2025-11-25 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_todo_priority_alter_todo_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('user', 'priority')},
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('user', 'priority'), ('user', 'title')},
        ),
    ]
